### ISSUE TITLE
Question: usability

### ISSUE THREAD

**Issue by PangolinGiLA** [Doraemooonnn/android_device_xiaomi_haydn#1]
Hi,
I have xiaomi mi 11i phone and wanted to install LineageOS on it. How usable is this port? Why this device is not on official Lineage OS wiki?

**Comment by Doraemooonnn** [comment]
> Hi, I have xiaomi mi 11i phone and wanted to install LineageOS on it. How usable is this port? Why this device is not on official Lineage OS wiki?

I only use PixelExperience and mi 11i doesn't have official LineageOS

**Comment by PangolinGiLA** [comment]
I saw there is a branch here for LineageOS. That's why I'm asking. How good is it working?

**Comment by Doraemooonnn** [comment]
> 

I don't know about LineageOS I just love Pixel based ROM

**Comment by PangolinGiLA** [comment]
Oops sorry just realised I had two different repos open and asked on the wrong one. Sorry for bothering you!
